<a href="https://colab.research.google.com/github/Ju-06/2026-BDA/blob/main/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## numpy vstack()

In [162]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [164]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [166]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [167]:
c = np.arange(20,24).reshape(2,2)
c

array([[20, 21],
       [22, 23]])

In [168]:
np.vstack((a,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [169]:
np.vstack((a,b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [175]:
d = np.array([100, 200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [177]:
d = np.array([100, 200, 300]) #(2,2)배열이랑 1차원 배열이라 오류
np.vstack((a,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [178]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

## numpy.hstack()

In [180]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [182]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [185]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [187]:
c = np.array([[10,20], [30,40]])
c

array([[10, 20],
       [30, 40]])

In [189]:
np.hstack((a,c))
# (2,2)랑 (3,x)랑 합치기 불가

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [190]:
np.hstack((np.arange(3), np.arange(10,15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

## 배열 결합 연산 column_stack(), row_stack()

In [192]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [194]:
b = np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [195]:
np.c_[a,b]

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [199]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [201]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.c_[x,y]

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

NameError: name 'newaxis' is not defined

## stack



In [4]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
c = np.arange(1,6,2)
print(c)

[1 3 5]


In [6]:
import numpy as np

np.hstack((a, np.expand_dims(c, axis = 1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [8]:
np.hstack((a,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [7]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.c_[a,b] #column 이라는 의미의 c

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
np.column_stack( (a, b) )

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# ppt 26p r_ 뭐시기 x

In [18]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

x

array([[1, 2, 3]])

In [19]:
y

array([[4, 5, 6]])

In [20]:
x.shape, y.shape

((1, 3), (1, 3))

In [21]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [24]:
np.c_[x,y] #소괄호x 대괄호

array([[1, 2, 3, 4, 5, 6]])

In [25]:
np.c_[x,10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

## 난수

In [76]:
rg = np.random.default_rng(12345) # random number generater? rng
rg.random() # 0~1의 난수 [0,1) 0포 1미포

0.22733602246716966

In [61]:
rg.random()

0.7247813610920201

In [78]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [79]:
rg.random((3,4))

array([[0.59830875, 0.18673419, 0.67275604, 0.94180287],
       [0.24824571, 0.94888115, 0.66723745, 0.09589794],
       [0.44183967, 0.88647992, 0.6974535 , 0.32647286]])

In [80]:
rg.random((2, 3,4))

array([[[0.73392816, 0.22013496, 0.08159457, 0.1598956 ],
        [0.34010018, 0.46519315, 0.26642103, 0.8157764 ],
        [0.19329439, 0.12946908, 0.09166475, 0.59856801]],

       [[0.8547419 , 0.60162124, 0.93198836, 0.72478136],
        [0.86055132, 0.9293378 , 0.54618601, 0.93767296],
        [0.49498794, 0.27377318, 0.45177871, 0.66503892]]])

In [84]:
rg = np.random.default_rng(1)
rg.integers(low=0, high = 10,size = 3) # (0,10] 0에서 10까지의 정수

array([4, 5, 7])

In [134]:
rg.integers(low=0, high = 20,size = (3,4))

array([[18,  1,  6, 19],
       [15,  8,  1, 12],
       [ 3, 18,  5,  8]])

In [136]:
rg.integers(1,7,(3,4))

array([[4, 3, 4, 5],
       [3, 3, 3, 5],
       [4, 3, 6, 2]])

In [137]:
rg = np.random.default_rng(1)
rg.standard_normal(3) #표준 정규분포 실수 난수


array([0.34558419, 0.82161814, 0.33043708])

In [138]:
rg.standard_normal((3,4))

array([[-1.30315723,  0.90535587,  0.44637457, -0.53695324],
       [ 0.5811181 ,  0.3645724 ,  0.2941325 ,  0.02842224],
       [ 0.54671299, -0.73645409, -0.16290995, -0.48211931]])

## 배열 결합 연습

In [139]:
p = np.arange(1,7).reshape(2,3)
q = np.arange(11,17).reshape(2,3)
r = np.arange(21,27).reshape(2,3)

p,q,r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [140]:
np.vstack( (p,q,r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
a,b,c

In [141]:
np.hstack((a,b,c))

array([1, 2, 3, 4, 5, 6, 1, 3, 5])

In [142]:
np.hstack((p,q,r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [143]:
np.column_stack((a,b,c))

array([[1, 4, 1],
       [2, 5, 3],
       [3, 6, 5]])

In [144]:
np.column_stack((p,q,r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [145]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 1, 3, 5])

In [147]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6, 1, 3, 5])

In [148]:
np.concatenate((a,b,c), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [149]:
np.concatenate((a,b,c), axis=None)

array([1, 2, 3, 4, 5, 6, 1, 3, 5])

In [150]:
np.concatenate((a,b,c), axis=-1)

array([1, 2, 3, 4, 5, 6, 1, 3, 5])

In [151]:
np.concatenate((p,q,r), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [152]:
np.concatenate((p,q,r), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [153]:
np.concatenate((p,q,r), axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [154]:
np.concatenate((p,q,r), axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [155]:
np.c_[a,b,c] #1D -> 2D

array([[1, 4, 1],
       [2, 5, 3],
       [3, 6, 5]])

In [156]:
np.column_stack([a,b,c])

array([[1, 4, 1],
       [2, 5, 3],
       [3, 6, 5]])

In [157]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 1, 3, 5])

In [159]:
np.r_[p,q,r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])